version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: UEPB
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
